version: '3.3'

services:
  haproxy_ssl_test:
    build: ./
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './docker-entrypoint.sh/:/docker-entrypoint.sh'
      - './haproxy/:/usr/local/etc/haproxy'
      - './rsyslog/99-haproxy.conf:/etc/rsyslog.d/99-haproxy.conf'
      - './bin/haproxy_ocsp_updater:/usr/local/bin/haproxy_ocsp_updater'
    entrypoint: '/docker-entrypoint.sh'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
